#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V8
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pysi")]
	public partial class BancoDadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblInterest(tblInterest instance);
    partial void UpdatetblInterest(tblInterest instance);
    partial void DeletetblInterest(tblInterest instance);
    #endregion
		
		public BancoDadosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pysiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblInterest> tblInterests
		{
			get
			{
				return this.GetTable<tblInterest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblInterests")]
	public partial class tblInterest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _txtName;
		
		private string _txtEmail;
		
		private System.DateTime _dteDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntxtNameChanging(string value);
    partial void OntxtNameChanged();
    partial void OntxtEmailChanging(string value);
    partial void OntxtEmailChanged();
    partial void OndteDateTimeChanging(System.DateTime value);
    partial void OndteDateTimeChanged();
    #endregion
		
		public tblInterest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string txtName
		{
			get
			{
				return this._txtName;
			}
			set
			{
				if ((this._txtName != value))
				{
					this.OntxtNameChanging(value);
					this.SendPropertyChanging();
					this._txtName = value;
					this.SendPropertyChanged("txtName");
					this.OntxtNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string txtEmail
		{
			get
			{
				return this._txtEmail;
			}
			set
			{
				if ((this._txtEmail != value))
				{
					this.OntxtEmailChanging(value);
					this.SendPropertyChanging();
					this._txtEmail = value;
					this.SendPropertyChanged("txtEmail");
					this.OntxtEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dteDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime dteDateTime
		{
			get
			{
				return this._dteDateTime;
			}
			set
			{
				if ((this._dteDateTime != value))
				{
					this.OndteDateTimeChanging(value);
					this.SendPropertyChanging();
					this._dteDateTime = value;
					this.SendPropertyChanged("dteDateTime");
					this.OndteDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
